// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// choose_options
List choose_options(NumericVector toki1, NumericVector toki2, NumericVector res_token_i_1, NumericVector res_token_i_2);
RcppExport SEXP diffrprojects_choose_options(SEXP toki1SEXP, SEXP toki2SEXP, SEXP res_token_i_1SEXP, SEXP res_token_i_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type toki1(toki1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type toki2(toki2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res_token_i_1(res_token_i_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res_token_i_2(res_token_i_2SEXP);
    rcpp_result_gen = Rcpp::wrap(choose_options(toki1, toki2, res_token_i_1, res_token_i_2));
    return rcpp_result_gen;
END_RCPP
}
// dist_mat_absolute
IntegerMatrix dist_mat_absolute(IntegerVector x, IntegerVector y);
RcppExport SEXP diffrprojects_dist_mat_absolute(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dist_mat_absolute(x, y));
    return rcpp_result_gen;
END_RCPP
}
// which_dist_min_absolute
List which_dist_min_absolute(IntegerVector x, IntegerVector y);
RcppExport SEXP diffrprojects_which_dist_min_absolute(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(which_dist_min_absolute(x, y));
    return rcpp_result_gen;
END_RCPP
}
