# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' (choose from a number of pre-sorted options)
#' takes a vector pair of toki1 / toki2 and a vector pair of res_token_i_1 /
#' res_token_i_2 and chooses so that each 1st and exh 2nd value only is used
#' where res_token_i_x identiefies already used items.
#' @param toki1 first number of number pair to choose from
#' @param toki2 second number of number pair to choose from
#' @param res_token_i_1 already used first numbers
#' @param res_token_i_2 already used second numbers
#' // @keywords internal
choose_options <- function(toki1, toki2, res_token_i_1, res_token_i_2) {
    .Call('diffrprojects_choose_options', PACKAGE = 'diffrprojects', toki1, toki2, res_token_i_1, res_token_i_2)
}

#' (function to calculate distance matrix of integers)
#' takes vector of size n and vector of size m and gives back matrix of n rows and m columns
#' @param x a vector of type numeric
#' @param y a vector of type numeric
#' @keywords internal
dist_mat_absolute <- function(x, y) {
    .Call('diffrprojects_dist_mat_absolute', PACKAGE = 'diffrprojects', x, y)
}

#' (function to calculate minimum and position of minimum)
#' takes vector of size n and vector of size m and gives back list with
#' vectors of size n (minimum distance and location of minimum in y)
#' @param x a vector of type integer
#' @param y a vector of type integer
#' @keywords internal
which_dist_min_absolute <- function(x, y) {
    .Call('diffrprojects_which_dist_min_absolute', PACKAGE = 'diffrprojects', x, y)
}

