# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' (function to calculate distance matrix of integers)
#' takes vector of size n and vector of size m and gives back matrix of n rows and m columns
#' @param x a vector of type numeric
#' @param y a vector of type numeric
#' @keywords internal
dist_mat_absolute <- function(x, y) {
    .Call('diffrprojects_dist_mat_absolute', PACKAGE = 'diffrprojects', x, y)
}

#' (function to calculate minimum and position of minimum)
#' takes vector of size n and vector of size m and gives back list with
#' vectors of size n (minimum distance and location of minimum in y)
#' @param x a vector of type integer
#' @param y a vector of type integer
#' @keywords internal
which_dist_min_absolute <- function(x, y) {
    .Call('diffrprojects_which_dist_min_absolute', PACKAGE = 'diffrprojects', x, y)
}

